# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6dbe21d548765d276b0e3d9eb61384f28d0f4bc806bdda648f44b573977eb34bcf3d0e6ff33b06340001aec7c1029e3d3487af31f3b0dc08d4c47ebf8dae70

test:
  secret_key_base: 0a74f2e6f926729fc24858fd66769b94e67034f51e71440878b821ea2ae9a4485f6b3925b16f655203f4744b86a62148cb0b37f9ee7f347e346225128cc3e686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
